default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  host: localhost

development:
  <<: *default
  database: db-development

test:
  <<: *default
  database: db-test
  user: root
  password: password

production:
  <<: *default
  database: db-production
